### ISSUE TITLE
Investigate and fix page load time

### ISSUE THREAD

**Issue by zhibek** [babanesma/camelcase_website#18]
Initial page load time is usually >20secs - during this time user experiences a blank screen.

The following report (taking ~11sec on a fibre connection) shows the number/size of assets that are loaded:
http://www.webpagetest.org/result/150817_79_8074c379a32e749b63d284740d0c57d7/

In summary - 79 requests totalling 5MB. We need to reduce the number of assets that are being loaded - some of the assets are loaded, but not shown on the page (e.g. http://dev.camelcasetech.com/sites/all/themes/wego/img/samples/slideshow/item-1.jpg), other assets need to be combined (e.g. the separate js + css files).

It's also likely that some JS is hiding the loaded content until the full page load is complete. Given the full page load takes ~20sec, it's likely to be better to show the partly loaded page because it will give the user the perception that the page is loading faster.

Lastly, some of the images are excessively large. All images should be optimised to ensure they're not larger than they have to be (JPG images should be optimised to have a quality level of 80 set).

We should target no more than **30 requests**, totalling less than **1.5MB** for the page load. The initial **page load** should not take more than **5sec** and some **visible content** should be available after **1sec**.

**Comment by zhibek** [comment]
Flagging @babanesma & @ahmedelbougha for task prioritisation.

**Comment by babanesma** [comment]
Latest webpagetest result 

http://www.webpagetest.org/result/150908_WP_98c82d6a473885009025442c3a2e75c4/

Still the caching in the first time is taking a long time

**Comment by zhibek** [comment]
Thanks for updating the latest test result. Most of the results are worse now than before (time to document complete up to 23sec from 11sec and requests up to 109 from 76) so we need to do more to fix this. On the plus side, the size of the assets is down to 3.6MB from 5MB and the page rendering no longer shows a completely blank screen for a long period at the start of the page load and this is a big improvement.

If there are specific areas which are causing the page load to take so long then lets evaluate whether we'd be better off removing/disabling them or putting in a replacement. For example, if the Google Maps JS is a specific problem then we could always use a static map instead (static map goes directly in an <img> tag rather than requiring javascript - see https://developers.google.com/maps/documentation/static-maps/).

**Comment by zhibek** [comment]
I've optimised the largest images according to webpagetest.org and I've removed a redundant image from being requested.

This is the latest webpagetest result:
http://www.webpagetest.org/result/160226_JJ_e4ea8bb806fbdcec101264bb49d617da/

Vital stats are:
Number of requests: 44
Request size: 1.57MB
Page load time: 4.0sec
Visible content after: 2.4sec

It's quite an improvement from before - its probably good enough to start with, although I think we should try to reduce the number of requests further (44 is still too high).

**Comment by zhibek** [comment]
Closing as good enough for now (as we develop more features on the website, we'll need to re-check webpagetest.org to make sure page load time and page weight isn't rising again).
