### ISSUE TITLE
Remove rollover placeholder icons text from "DEVELOP","CONSULT" & "TEST" slides

### ISSUE THREAD

**Issue by zhibek** [babanesma/camelcase_website#19]
The icons on "DEVELOP","CONSULT" & "TEST" slides have placeholder text saying "BUY", "IT", "NOW" when a user rolls over them.

Remove both this text ("BUY", "IT", "NOW") and the symbols that are shown before rollover (the symbols don't have any relation to the slides) just leaving the orange coloured diamond shapes.

The screenshot below highlights the area:
![camelcase_website_buyitnow_text](https://cloud.githubusercontent.com/assets/1309381/18247824/a926c43a-736c-11e6-9e89-0f182e85193c.png)

**Comment by ahmedelbougha** [comment]
Reviewed

**Comment by zhibek** [comment]
Looks good - closing.
