### ISSUE TITLE
Team photo aspect ratios are incorrect (need to be exactly square)

### ISSUE THREAD

**Issue by zhibek** [babanesma/camelcase_website#20]
The images used for the team photos are the wrong aspect ratio, which means they don't fill the circle correctly. The images need to be square (i.e. exactly the same width and height) so that no orange background colour is shown inside the circles.

Crop each profile photo so that it is exactly 160x160px (do not squeeze the images, simply crop the area to leave the area around the face of each person only). Currently the photos for Adham, Yassin and Reda have almost the right aspect ratio so they only need small changes, while the photos for everyone else (myself, Rashad, AbdElRahman, AbdElMoniem) need more cropping off the top/bottom of the image to make them work. We also need an image for Labib.

The screenshot below highlights the problem:
![camelcase_website_team_photo_ratio](https://cloud.githubusercontent.com/assets/1309381/18247911/4fc23108-736d-11e6-8408-3eeb5b33599b.png)

Please use this photo (its already square, it just needs to be resized to 160x160px) for this (when I get a better portrait photo, I'll replace this!):
![john_portrait](https://cloud.githubusercontent.com/assets/1309381/18248141/7f544b80-736e-11e6-85f5-204a6da3a21c.jpg)

**Comment by ahmedelbougha** [comment]
Reviewed

**Comment by zhibek** [comment]
Looks good - closing.

Noting the new related tickets #22 & #23.
