### ISSUE TITLE
"What we do" text finishes mid-sentence

### ISSUE THREAD

**Issue by zhibek** [babanesma/camelcase_website#21]
The "What we do" text finishes mid-sentence for some of the sections. Every section should have complete sentences, finishing with a full stop.

Please use the follow text for each section (with the exact punctuation specified - full stops and commas **should not** have spaces before them, only afterwards). Please note **TEST should be moved to be the last section**.

```
CONSULT
Use our experience to plan and execute your product - delivering projects to an international standard.

DEVELOP
We develop large scale web applications and websites - with experience delivering sites with a turnover of over $10m.

TEST
Increase application quality with automated testing - unit testing, integration testing, behavioural testing.
```

The screenshot below highlights the area:
![camelcase_website_whatwedo_text_incomplete](https://cloud.githubusercontent.com/assets/1309381/18248172/a6343d46-736e-11e6-90fe-3834a6e9ec41.png)

**Comment by ahmedelbougha** [comment]
Reviewed

**Comment by zhibek** [comment]
Looks good - closing.

Noting the new related ticket #24.
